### ISSUE TITLE
Ansible should load .env file based on environment being deployed

### ISSUE THREAD

**Issue by mikem** [Tahi-project/ihat#10]
Currently in `ansible/inventory.rb` the [`.env.staging` file is hardcoded](https://github.com/Tahi-project/ihat/blob/f9092c1b2dbacad58b2b8c4e2e3124fbe901f932/ansible/inventory.rb#L19). This file should be loaded based on the environment being deployed.

An attempt to change this line to `Dotenv.load!(".env.#{ENV['ENV']")` results in the following stack trace:

```
$ ansible-playbook ansible/db-playbook.yml -i ansible/inventory.rb --extra-vars "ENV=production"
Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/1.8.4/libexec/bin/ansible-playbook", line 326, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/Cellar/ansible/1.8.4/libexec/bin/ansible-playbook", line 162, in main
    inventory = ansible.inventory.Inventory(options.inventory, vault_password=vault_pass)
  File "/usr/local/Cellar/ansible/1.8.4/libexec/lib/python2.7/site-packages/ansible/inventory/__init__.py", line 118, in __init__
    self.parser = InventoryScript(filename=host_list)
  File "/usr/local/Cellar/ansible/1.8.4/libexec/lib/python2.7/site-packages/ansible/inventory/script.py", line 49, in __init__
    self.groups = self._parse(stderr)
  File "/usr/local/Cellar/ansible/1.8.4/libexec/lib/python2.7/site-packages/ansible/inventory/script.py", line 57, in _parse
    self.raw  = utils.parse_json(self.data)
  File "/usr/local/Cellar/ansible/1.8.4/libexec/lib/python2.7/site-packages/ansible/utils/__init__.py", line 552, in parse_json
    results = json.loads(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by mikem** [comment]
Moved this issue to Tracker.
